[package]
name = "acid-state"
description = "easy persistence for rust"
license = "Apache-2.0"
version = "0.1.0"
authors = ["Tyler Neely <t@jujit.su>"]

[dependencies]
rustc-serialize = "0.3"
bincode = "0.5"
lazy_static = "0.2"
